name: Go Test for PQC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CICD_SA_JSON: ${{ secrets.CICD_SA_JSON }}
  CICD_AWS_ACCESS_KEY: ${{ secrets.CICD_AWS_ACCESS_KEY }}    
  CICD_AWS_ACCESS_SECRET: ${{ secrets.CICD_AWS_ACCESS_SECRET }} 
  CICD_AWS_REGION: ${{ secrets.CICD_AWS_REGION }} 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run tests root
        run: go test -v .

      - name: Run tests PEM
        working-directory: mldsa
        run: go test -v .

      - name: Run tests GCP
        working-directory: gcpkms
        run: go test -v .

      - name: Run tests AWS
        working-directory: awskms
        run: go test -v .